### ISSUE TITLE
How to use omniauth to access users starred repos

### ISSUE THREAD

**Issue by iandesj** [intridea/omniauth-github#34]
I've decided to use this gem in conjunction with the github_api gem. However, I'm not 100% sure how to use the authorization I've received back from github to use the github_api gem. I know Github.new basic_auth: 'user:password' and Github.new  oauth_token 'token' but I'm not exactly sure how to get that token as a response. Any help would be appreciated.

**Comment by nomoregrapes** [comment]
When the user logins in using omniauth and is redirected to your app, you want to store `auth.credentials.token`, this allows you later to do 
`github = Github.new oauth_token: auth.credentials.token`

Although I'm not sure this is the best way to be doing things, and it seems to confuse it.
If you setup omniauth with enough scopes, I think you should be able to make other calls to Github for data without needing the github_api gem. This I am still trying to work out.
