### ISSUE TITLE
Ominauth github returns unverified email addresses 

### ISSUE THREAD

**Issue by SamSaffron** [intridea/omniauth-github#36]
Github API will return unverified email addresses and omniauth github forwards this on, instead gem should check "verified" true https://developer.github.com/v3/users/emails/#list-email-addresses-for-a-user before sending back emails. Its a huge security hole cause people can easily impersonate.

**Comment by nileshtrivedi** [comment]
I see that this PR was merged 7 days ago: https://github.com/intridea/omniauth-github/commit/341254478d6f8c5439b49f1d14006cc8ae50befa but there hasn't been a release with this fix yet.

@mbleigh When will this release happen? Discourse and other apps are having to maintain their own forks because of this pending fix.

**Comment by chrisvfritz** [comment]
I'm also requesting a new release for this critical feature. For apps that access the GitHub API on behalf of users, which I'm guessing is most apps that include this gem, many requests will return errors until the email address is verified.

**Comment by tmilewski** [comment]
Working on getting access to push an update to RubyGems.

In the meantime, this will work...
`gem 'omniauth-github', git: 'https://github.com/intridea/omniauth-github.git', tag: '1.2.0'`

**Comment by SamSaffron** [comment]
@tmilewski  if you are stuck in 2-3 weeks and old gem owner can not be found try contacting @arthurnn

It is a security release after all which makes it a bit more important...

**Comment by arthurnn** [comment]
@mbleigh is the only gem owner of this gem on rubygems.org.
Let's wait for him. I will try to talk to him too.

**Comment by tmilewski** [comment]
@SamSaffron @arthurnn It's now live!

https://rubygems.org/gems/omniauth-github/versions/1.2.0

![Access Granted](https://media.giphy.com/media/3orif3NCyKZ61frBHa/giphy.gif)

**Comment by arthurnn** [comment]
Thanks everyone ❤️
