### ISSUE TITLE
CSRF detected

### ISSUE THREAD

**Issue by arg** [intridea/omniauth-github#37]
I'm using omniauth-github 1.1.2 with Sinatra. In development mode (application callback points to http://localhost:3000/auth/github/callback) I'm not able to authorize due to the error:
```
(github) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected
(github) Authentication failure! invalid_credentials: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected
```
It happens only in Chrome, in Firefox everything works fine.

The related code:
```ruby
use OmniAuth::Builder do
  provider :github, '11111', '22222222', scope: 'user:email'
end
```

**Comment by dpgailey** [comment]
I'm getting this in 2018. What changed?

**Comment by joshiefishbein** [comment]
Still getting this error in 2019. Only happens in Chrome, not in FF or Safari. Any ideas?

**Comment by heertheeswaran** [comment]
Still getting this error recently, Any ides?
