### ISSUE TITLE
User's organization list not populated

### ISSUE THREAD

**Issue by bwalsh** [intridea/omniauth-github#60]
Hi. Thanks for a great piece of code.  Got it working without a hitch.

My scope clause is set to:

```
scope: "user,repo,gist,read:org"
```

However, the only thing I'm getting back that looks like an org list is as follows

```
{
  "provider": .....
  "info":{
    .....
    }
  },
  "credentials":{
   .....
  },
  "extra":{
    "raw_info":{
       ....
      "organizations_url":"https://api.github.com/users/...user.../orgs",
       ... 
    }
  }
}
```

Then, if I visit that url, I get an empty array `[]`?

Any ideas on how to get a populated org list into the `create_with_omniauth()` callback?

Thanks for your time?

**Comment by tmilewski** [comment]
Is this still an issue for you @bwalsh?

**Comment by bwalsh** [comment]
Not currently in use. Thanks

**Comment by tmilewski** [comment]
Moving to close. Thanks!
