### ISSUE TITLE
Empty results on token

### ISSUE THREAD

**Issue by shreyaq3** [intridea/omniauth-github#62]
Hi,I'm making an app which used omniauth-github gem to generate user token with user and admin:org scope
Its giving me empty results while try to fetch an organization's members
This is the curl request I'm sending, with the token generated using the gem -
`curl -u shreyaq3:<omniauth toekn>  https://api.github.com/orgs/org_id/members`
And this is response -
`[
]`
I'm pretty  sure that the scopes are correct.

I'm using setup phase in omniauth to dynamically set the client id and secret
```
Rails.application.config.middleware.use OmniAuth::Builder do
   provider :github, setup: true, scope: "user,read:org,write:org,admin:org"
end

def setup
  request.env['omniauth.strategy'].options[:client_id] = app_id
  request.env['omniauth.strategy'].options[:client_secret] = app_secret
end
```
However when I manually create a token for the same scope using github's token generation tool, I get correct results
This is request -
 `curl -u shreyaq3:<github token>  https://api.github.com/orgs/org_id/members`
Response -
```
[
  {
    "login": "xxx",
    "id": yyy,
    ....
    "type": "User",
    "site_admin": false
  }
]
```

Could you tell me if what am I missing. Is there something wrong with the token or perhaps I'm missing a step in authentication?

**Comment by tmilewski** [comment]
The requests you have listed require different authentication methods.

When using the token provided by the app, you must do so in this fashion:
`curl https://api.github.com/?access_token=<token>`

So, in your case ...
`curl https://api.github.com/orgs/<org_id>/members?access_token=<token>`

Going to close this for now. Feel free to reopen should you have additional issues.
