### ISSUE TITLE
Please publish to rubygems

### ISSUE THREAD

**Issue by usbsnowcrash** [intridea/omniauth-github#63]
It seems like there are almost two years of changes merged into master that have not been published to rubygems.  Is this gem abandoned?

**Comment by tmilewski** [comment]
Working on getting access to do so.

In the meantime, this will work...
`gem 'omniauth-github', git: 'https://github.com/intridea/omniauth-github.git', tag: '1.2.0'`

**Comment by tmilewski** [comment]
@usbsnowcrash It's now live!

https://rubygems.org/gems/omniauth-github/versions/1.2.0

![Access Granted](https://media.giphy.com/media/3orif3NCyKZ61frBHa/giphy.gif)

**Comment by usbsnowcrash** [comment]
Awesome thanks @tmilewski
