### ISSUE TITLE
Warning Generated by requiring gem

### ISSUE THREAD

**Issue by jgnagy** [intridea/omniauth-github#64]
Requiring the 'omniauth-github' gem causes this warning:

```
WARN -- : You are setting a key that conflicts with a built-in method OmniAuth::AuthHash::InfoHash#name defined at /Users/jgnagy/.rvm/gems/ruby-2.3.1/gems/omniauth-1.3.2/lib/omniauth/auth_hash.rb:34. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
```

I believe this is caused by this line:

https://github.com/intridea/omniauth-github/blob/master/lib/omniauth/strategies/github.rb#L32

Perhaps call it something other than `name` in the info hash?

**Comment by tmilewski** [comment]
This conversation appears to be happening at a few levels. See: https://github.com/omniauth/omniauth/issues/872

It was introduced by the Hashie gem. I'd like to see how the conversation linked above progresses before making a move. While renaming the key is simple, it introduces breaking changes.

It's safe to continue using `omniauth-github` as-is for now.

**Comment by tmilewski** [comment]
Update: The Hashie maintainer will be introducing a way to disable this message. This will be implemented at the `omniauth` level rather than `omniauth-github`.

**Comment by jgnagy** [comment]
Closing given @tmilewski's comment. I look forward to the improvement / option from `omniauth`.
