### ISSUE TITLE
No emails are returned

### ISSUE THREAD

**Issue by beanieboi** [intridea/omniauth-github#68]
Hey,

first of all, thank you so much for `omniauth-github` it makes it so easy to integrate oauth!

I have 3 email addresses configured on my account and they are not private. since the last version bump
- `auth_hash['info']['email']` is nil,
- `auth_hash['extra']['all_emails']` is `[]`
- `auth_hash['extra']['raw_info']['email']` contains my primary email.

anything I can help with debugging?

**Comment by tmilewski** [comment]
Pushed to RubyGems as `1.2.2`

**Comment by beanieboi** [comment]
thank you so much! after the patch. `auth_hash['info']['email']` contains my email address. out of curiosity, I would expect that my primary email would show up in `auth_hash['extra']['all_emails']` as well, but it's still empty. is this on purpose?
