### ISSUE TITLE
The redirect_uri MUST match the registered callback URL for this application. 

### ISSUE THREAD

**Issue by kddeisz** [intridea/omniauth-github#72]
Hi there,

I'm trying to get this thing to work and for some reason it just will not. It's passing a `redirect_uri` param like `http://localhost:3000/auth/github/callback?code=...&state=...` and on the integration page the callback url is listed as `http://localhost:3000/auth/github/callback`. Has anyone ever hit this error?

**Comment by volmer** [comment]
I opened a pull request to fix this issue: #73
Feel free to use my fork in the meantime.

**Comment by tmilewski** [comment]
This has been pushed as `1.3.0`: https://rubygems.org/gems/omniauth-github

Thanks!
