### ISSUE TITLE
404 error message 

### ISSUE THREAD

**Issue by jedrekdomanski** [intridea/omniauth-github#76]
I am getting 404 error message after entering URL http://localhost:3000/auth/github

initializer.rb
```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :github, ENV['GITHUB_CLIENT_ID'], ENV['GITHUB_CLIENT_SECRET']
end
```
routes.rb
```
get '/auth/:provider/callback', to: 'sessions#create'
```
GitHub configuration:
Homepage URL

http://localhost:3000

Authorization callback URL
http://localhost:3000/auth/github/callback

![zrzut ekranu z 2017-10-24 16-20-33](https://user-images.githubusercontent.com/5911945/31955499-defd7820-b8e8-11e7-8855-1a0b21e7eee4.png)

**Comment by jedrekdomanski** [comment]
Nevermind, it appears that I had to wait like half a day for GitHub to start authorizing and responding to my requests after I registered a new app

**Comment by tmilewski** [comment]
👍
